### ISSUE TITLE
Yaml configuration not honored.

### ISSUE THREAD

**Issue by mike-hampton-float** [quarkiverse/quarkus-openapi-generator#131] opened 2022-09-01 21:39 UTC
My configuration is in a yaml file.

My openapi file is here crm-svc/service/src/main/openapi/sellerdeal.yaml

My application.yaml file has

```
quarkus:
  openapi-generator:
    codegen:
      spec:
        sellerdeal_yaml:
          base-package:
            com.floatfin.sellerdeal.openapi
```

## Expected
The generated interfaces have the package:

```
com.floatfin.sellerdeal.openapi;
```

## Actual
The generated interfaces have the package:

```
package org.openapi.quarkus.sellerdeal_yaml.api;
```

**Comment by ricardozanini** [comment] 2022-09-02 12:09
Hi @mike-hampton-float! Thanks for reporting it. I'll take a look.

**Comment by vladaman** [comment] 2022-09-06 16:26
I have same issue. There is different behavior  depending on how you run the generator.

1. `mvn clean quarkus:generate-code` doesn't honor configuration option and generates code with org.openapi.quarkus package
2. `mvn clean compile` generates code properly

**Comment by ricardozanini** [comment] 2022-09-06 19:24
hmm, it might be a bug in Quarkus, then. Thanks for sharing @vladaman. I'll take a look later this week.

**Comment by ricardozanini** [comment] 2022-09-06 19:25
By the way, @gastaldi @geoand, do you guys know or have you seen anything like this before?

**Comment by gastaldi** [comment] 2022-09-06 20:39
No idea, but is this reproducible using `application.properties` too?

**Comment by ricardozanini** [comment] 2022-09-08 17:30
No, using `application.properties` works. :(

**Comment by gastaldi** [comment] 2022-09-08 18:49
It may indicate that the YAML ConfigSource is not found during `quarkus:generate-code`. WDYT @aloubyansky ?

**Comment by hbelmiro** [comment] 2022-10-07 12:11
@gastaldi @aloubyansky 

When the implementation of `CodeGenProvider` runs, the quarkus-config-yaml extension has not yet been loaded.

https://github.com/quarkiverse/quarkus-openapi-generator/blob/98f70d2ee0aa5d53a82b56a7c8cffc821d1ca4cd/deployment/src/main/java/io/quarkiverse/openapi/generator/deployment/codegen/OpenApiGeneratorCodeGenBase.java#L52

Would that be the expected behavior or a bug?

**Comment by aloubyansky** [comment] 2022-10-07 21:31
It's a bug, imo. The yaml config source has been loaded by that time but the config instance passed to the code generator doesn't include it.
@radcortez this looks like a consequence of https://github.com/quarkusio/quarkus/pull/21887 and https://github.com/quarkusio/quarkus/commit/ff95ddfb5aa82ad67688c55a43c6815af622820c that resulted in https://github.com/quarkusio/quarkus/blob/main/core/deployment/src/main/java/io/quarkus/deployment/CodeGenerator.java#L156-L162 Could we do better here?

**Comment by aloubyansky** [comment] 2022-10-07 21:50
It seems like we don't want to load config sources from the app module itself but do want to support those found in the dependencies (whether they belong to the same multi module project or not). We should be able to achieve that with classpath filtering.

**Comment by aloubyansky** [comment] 2022-10-07 22:23
Here is a sketch https://github.com/aloubyansky/quarkus/commit/126c5afa28623e717879a86349491e9431ff87f7 @radcortez am I missing something?

**Comment by aloubyansky** [comment] 2022-10-07 22:56
Sorry, disregard the previous one.
Here is a sketch https://github.com/aloubyansky/quarkus/commit/309480dce3fc08e5beeb5246ffdd4be6f1a9e19a @radcortez am I missing something?

**Comment by radcortez** [comment] 2022-10-10 12:49
Yes, commented on the commit :)

**Comment by ricardozanini** [comment] 2022-10-10 14:30
Thanks guys!

**Comment by hbelmiro** [comment] 2022-10-14 13:10
Thanks for the quick fix @aloubyansky and @radcortez.
However, this extension needs exactly the config that is in the root app, which is not contemplated in the fix.
I think there's a good reason for not existing a YAML alternative for [ApplicationPropertiesConfigSourceLoader](https://github.com/quarkusio/quarkus/blob/37a87a71df500f7557c603df209e5687962ffd49/core/runtime/src/main/java/io/quarkus/runtime/configuration/ApplicationPropertiesConfigSourceLoader.java), but I'll ask anyway. Wouldn't it be possible to create a YamlPropertiesConfigSourceLoader to cover this use case?

**Comment by aloubyansky** [comment] 2022-10-14 13:17
@hbelmiro do you have a config or a config provider impl? Unless it's the config provider, it should work. Is there a chance you could give it a try? You'd need to build the main branch of Quarkus. Let me know if you need help/instructions to do that.

**Comment by hbelmiro** [comment] 2022-10-14 13:28
@aloubyansky I tried and it didn't work. I might have done something wrong though.

The scenario is the following:
The user creates a Quarkus app with a src/main/resources/application.yaml and the quarkus-openapi-generator dependency (this extension). During a `mvn compile`, this extension needs to read the config from application.yaml to perform its job.

Should it work?

**Comment by aloubyansky** [comment] 2022-10-14 13:29
Yes. Do you have a reproducer ready to try?

**Comment by aloubyansky** [comment] 2022-10-14 13:32
Do you have `quarkus-config-yaml` among the project's dependencies?

**Comment by hbelmiro** [comment] 2022-10-14 13:35
I definitely did something wrong. It's not using Quarkus 999-SNAPSHOT.
I'll try again and if it doesn't work, I'll provide a reproducer.

> Do you have quarkus-config-yaml among the project's dependencies?

Yes.

**Comment by hbelmiro** [comment] 2022-10-14 14:52
@aloubyansky It worked. Sorry for wasting your time. Thanks for the help :)

@ricardozanini we can close this issue.

**Comment by aloubyansky** [comment] 2022-10-14 14:56
Thanks for confirming @hbelmiro!

**Closed** 2022-10-14 15:53 UTC
Labels: bug
